### ISSUE TITLE
Modelar e implementar lógica de cambio de canal de compra

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#10]
Se requiere: 

Definir el modelado de datos que se llevara a cabo para el cambio de canal

en caso de ser necesario se deberán crear modelos adicionales con la finalidad de identificar el tipo de usuario y el canal al que corresponde 

Esto funcionara como modelo inicial posteriormente sera actualizada al momento de importar los usuarios 

Como criterio de aceptación se deberá generar el modelo de datos a nivel de diagrama  

investigar si el framework cumple con lo requerido

en caso de existir una gema que pueda solventar lo planteado implementarla

implementar los modelos creados 

Test unitario

**Comment by LeonardoSantis-AcidLabs** [comment]
Trabajo inicial en layout de sitio y definición de marco de trabajo para vistas realizado:

PR:
https://github.com/Departamento-TI/cenabast-tienda/pull/21

Añadido TailwindCSS
Importadas definiciones de colores de Figma
Añadido ViewComponent y Lookbook para el desarrollo de view components (piezas reutilizables de la interfaz de usuario)
Implementado el componente de botón
Implementado (solo visualmente, el comportamiento está en progreso) el componente de header
Añadida `debugger` gem
Parcheado Nokogiri a la versión 1.16.2
Añadida documentación de pautas para la implementación de view components
Añadidas pruebas relacionadas con componentes y modelos

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/07)
Avance en diseño propuesta solución.
Implementación para cambiar canal de compra basada en Spree::Store
Creada logica para cambio de tienda
Falta probar interacción ejemplo con frontend, seeds de store
comportamient store default
Escritos tests relacionados a modelo

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/08)
Integración de logica para cambio de canal de compra basada en Spree::Store terminada.
Interacción (base) con frontend realizada. Usuario logeado puede cambiar canal de compra desde header del sitio.
Sitio guarda preferencia de Canal de compra. Permite renderizar contenido con logicas diferenciadas. Seleccionar productos disponibles especificos por canal de compra (Spree::Store), etc.
Test unitarios finalizados (agregados nuevos test, correcciones en tests existentes)
