### ISSUE TITLE
Error en el carro cuando se cambia de solicitante

### ISSUE THREAD

**Issue by nmella** [Departamento-TI/cenabast-tienda#102]
Hola @LeonardoSantis-AcidLabs 

Cuando cambio de solicitante en el header, el carro se actualiza correctamente (comportamiento esperado).

Sin embargo, cuando cambio el destinatario, a pesar que me muestra un nuevo carro, al agregar un producto éste se agregar al carro previo (al Solicitante previo)

Aquí está la prueba que hice:

https://youtu.be/90zdjbcIXQ8

Ojalá lo puedas replicar en tu local. Gracias.

cc: @Claudioten, @Saulaccid, @FelipeFabio-Acid

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola, muy buenos dias Nicolas 🙋‍♂️,

En efecto notamos un comportamiento borde para los usuarios administradores.
Posterior al cambio de destinatario/solicitante, el carro de compra no se estaba refrescando para estos usuarios.

Voy a mergear el PR
https://github.com/Departamento-TI/cenabast-tienda/pull/107
con una corrección.

Al menos en mi ambiente local, ya funciona correctamente.
Comparto evidencia:

https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/427fabbf-463d-49f1-8c18-cfdeef4d889c

Saludos!

**Comment by nmella** [comment]
OK gracias ! Lo pruebo.

**Comment by nmella** [comment]
Validado, funciona impeque. 🙌
