### ISSUE TITLE
Error al cambiar de Tienda => No existe la categoría

### ISSUE THREAD

**Issue by ncmella** [Departamento-TI/cenabast-tienda#105]
Hola @LeonardoSantis-AcidLabs 

Necesitamos resolver este problema cuando la categoría no existe en la tienda ([error](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/a0fb284d-6619-445c-8507-b618da10925e))

**No se puede crear la categoría** en la tienda "intermediación" cuando ésta ya existe en la tienda "ecommerce". Arroja [este](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/35a93338-2700-4d7d-aa24-70fb90c185dd) error. 

Para replicar el error:

1. Loggear en la tienda. 
2. Estando en la tienda (o canal) ecommerce, hacer click en la categía fármacos (o cualquier categoría que exista en ecommerce).
3. Estando en la ruta de fármacos, cambiar la tienda al canal "intermedación".
4. Aparece el error porque la categoría **no existe**. 

=> [video](https://youtu.be/AwqaYYV48BE).

Gracias !

cc: @Saulaccid, @Claudioten

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola Nicolas, muy buenas tardes 👋
En efecto, puedo replicar el comportamiento,
Spree intenta buscar un taxon no disponible para el sitio, por lo que arroja la excepción `ActiveRecord::RecordNotFound`.

Como estamos probando en ambientes de desarrollo, el sistema muestra la excepción con su stacktrace.
En ambientes productivos, Rails está configurado para mostrar la pagina de 404 en esos casos.
![image](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/b79471c8-127a-467f-a6a7-08bd949f168e)
https://guides.rubyonrails.org/action_controller_overview.html#the-default-500-and-404-templates

De todos modos, me parece mejor realizar un redirect a la ruta raiz (/). Para evitar esos comportamientos inesperados
Que opinas?

Quedo atento,
Saludos!

**Comment by ncmella** [comment]
Si, con un redirect a la raíz del sitio estaría perfecto, gracias.

**Comment by LeonardoSantis-AcidLabs** [comment]
Perfecto, mergeé el PR a main con el cambio.

**Comment by nmella** [comment]
Gracias. Funciona OK. 🙌
