### ISSUE TITLE
Precio en PDP && Punto en vez de Compa

### ISSUE THREAD

**Issue by nmella** [Departamento-TI/cenabast-tienda#108]
Hola @Saulaccid 

Hay 2 pequeños arreglos que debemos corregir:

1. En todas las páginas (PDP, PLP, Carro, Checkout) el separador de miles tiene coma (,). Debería ser un punto (.). 
2. Al precio de la PDP por favor agregar el signo pesos ($) como prefijo al número. 

Eso, gracias !

cc: @LeonardoSantis-AcidLabs @Claudioten

**Comment by Saulaccid** [comment]
Hola @Nicolas Mella Maldonado ***@***.***>

Cabe acotar que estos cambios son más cosméticos, no de funcionamiento o
alcance

**Comment by nmella** [comment]
Gracias @LeonardoSantis-AcidLabs 

Validé y funcionó OK. 

> Cabe acotar que estos cambios son más cosméticos, no de funcionamiento o alcance

@Saulaccid no entiendo el punto a qué te refieres. ¿Significa que está fuera de la garantía cuando es "cosmético" ? Aún cuando en la imagen de prototipo en Figma estuviese con punto (.) y con signo pesos ($) ?
