### ISSUE TITLE
Servicio API sin direcciones

### ISSUE THREAD

**Issue by ncmella** [Departamento-TI/cenabast-tienda#14]
Hola @pzunigacl 

De las APIs de [tienda](https://testaplicacionesweb.cenabast.cl:7001/interoperabilidad/servicios/docs/index.html), este servicio retorna las relaciones de los usuarios compradores con los organismos solicitantes y destinatario.:

```ruby
GET '{{host}}/interoperabilidad/servicios/v1/tienda/destinatarios/16338556' \
--header 'Authorization: Bearer {{token}}'
```
![2023-11-08_10-34](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/be36d788-376a-4d98-9d72-065dac2549b1)

Sin embargo, el campo de direcciones `direccionDespacho` viene **vacio** y necesitamos las direcciones o puerto de descarga asociadas. Además de la dirección, también necesitaremos la **región** y **comuna**. 

Gracias !

cc: @Claudioten, @rsalazarb

**Comment by rsalazarb** [comment]
Hola @ncmella, actualizamos la vista. Por favor, validar que te aparecen las direcciones.

**Comment by ncmella** [comment]
Gracias @rsalazarb ! Sí, ahora sí viene la dirección. 

¿Será posible agregar a la respuesta de la API la **region** y **comuna** ?

**Comment by nmella** [comment]
Cerraré este issue por ahora. Cuando tengamos la API para inyectar pedido veremos como obtener las direcciones de los organismos.
