### ISSUE TITLE
Catálogo de Materiales

### ISSUE THREAD

**Issue by nmella** [Departamento-TI/cenabast-tienda#23]
Hola @fgarciacena,

El catálogo de materiales al parecer es antiguo ?. No encontré ningún producto ZCEN que tuviese un contrato "activo".

Me explico:

- Tanto la API "/api/v2/Public/contrato" como "/api/v2/material/listacatalogo" retornan 13080 productos [responsepublic.xlsx](https://github.com/Departamento-TI/cenabast-tienda/files/14214097/responsepublic.xlsx). 
De todos los productos, sólo 8465 son del tipo ZCEN (5000*****).
- Los últimos códigos ZCEN del listado son 500014015, 500014013, 500014010, 500014009, 500014008 ...
- Al consultar la API de contratos ["https://testaplicacionesweb.cenabast.cl:7001/interoperabilidad/servicios/v1/tienda/contratos/500014015"](https://testaplicacionesweb.cenabast.cl:7001/interoperabilidad/servicios/v1/tienda/contratos/500014015) por un producto ZCEN, la API responde:

  - **Sin contrato**: {  "message": "Contratos no encontrados."}
  - **Con fechas antiguas** => ... "FechaInicialContrato": "202203", "FechaFinalContrato": "202308".

Por favor tu ayuda para obtener contratos activos de productos ZCEN.

cc: @Claudioten

**Comment by nmella** [comment]
Hola @fgarciacena

La API del catálogo de materiales es la más urgente. También habíamos quedado con Pedro de incluir la API de catálogo de materiales dentro del grupo de API de tienda ([esta](https://testaplicacionesweb.cenabast.cl:7001/interoperabilidad/servicios/docs/index.html)).

Gracias.

cc: @Claudioten

**Comment by fgarciacena** [comment]
Hola @nmella! Te comento que estamos restaurando unas vistas que sirven como input para la API. El Endpoint de catalogo de materiales ya se encuentra en la api de la tienda. Una vez restaurada las vistas, se revisará el problema de los productos sin contratos.

Te aviso ante cualquier novedad.
Saludos!
