### ISSUE TITLE
Clave Única

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#26]
Idealmente la integración con Clave Única debe realizarse con la aplicación de Single Sign On
“Keycloak”. De lo contrario, la integración deberá hacerse directamente desde la tienda de Spree
Commerce. La solución se deberá resolver en conjunto con el equipo técnico. Actualmente ya se
encuentra habilitada la plataforma Keycloak, que a su vez ya está integrada con el ambiente de desarrollo de Clave Única.

Sólo faltaría:

Integrar la tienda de Spree Commerce con Keycloak, utilizando el protocolo de autenticación
OpenID Connect. Posiblemente se podría utilizar la gema “Device” para Spree.

Criterio de aceptación:

Lograr un redirect a la plataforma de Cenabast al pasar por el Keycloak

Deshabilitar el login nativo de spree

Deshabilitar el Registro nativo de spree

Deshabilitar la recuperación de contraseña

No poder acceder a la tienda sin iniciar sesión - Con cualquier url sin sesión se debe hacer un redirect al login

**Comment by LeonardoSantis-AcidLabs** [comment]
(2023/02/12)
Trabajo en configuración de Keycloak reinstaurada en docker-compose de proyecto

**Comment by LeonardoSantis-AcidLabs** [comment]
(2023/02/13)
Construcción de vista de login en relación a maqueta en Figma


![Image](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/197436df-8d51-489c-bbaa-173da29afa42)


Trabajo en progreso en: desabilitar login/registro, habilitar login con clave unica

**Comment by LeonardoSantis-AcidLabs** [comment]
https://github.com/Departamento-TI/cenabast-tienda/pull/37

(2024/02/15)
* Disabled registration, remember password, confirm accout devise routes
* Added omniauth gem to manage single sign-on of Devise spree_users using Keycloak/Clave Unica
* Connect Omniauth with login frontend
* Add DEVELOPER_SILENCE_LOGS option for dev envs
* Add related docs/specs
