### ISSUE TITLE
Autenticación de servicio por Token

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#27]
La información actualizada de las API estará disponible en la documentación Dado que existen 2 modelos distintos de APIs (“proyectosti”, “WebApi2”), cada uno tiene su propio “endpoint” de autenticación. Se requiere el valor del token de cada uno de estos servicios para poder
consultar el resto de las APIs.

Por lo cual se debe crear el método para realizar la autenticación y guardar la data por el tiempo de vida del token 

Criterio de aceptación:

Crear los servicio de autenticacion 

Crear el modelo para customizar el tiempo de vida del token 

Crear un metodo para evaluar si el token esta vencido o si no existe pueda crearlo de nuevo 

Obtener los token de ambos servicios

**Comment by nmella** [comment]
> Dado que existen 2 modelos distintos de APIs (“proyectosti”, “WebApi2”)

Finalmente sólo utilizaremos 1 grupo de APIs...este:

https://testaplicacionesweb.cenabast.cl:7001/interoperabilidad/servicios/docs/index.html

**No utilizaremos** la API “proyectosti” ni “WebApi2”.

**Comment by LeonardoSantis-AcidLabs** [comment]
@nmella 

Entendido, la autenticación de token solo va a comprender ese conjunto de APIs

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/16)
Instalación de mage-ai en ambiente local
Pruebas de creación de pipeline con extracción de token desde API de Cenabast.

(2024/02/19)
Creación de servicio para obtención de token en Ruby.
Fijé un ejemplo desde MageAI. sin embargo dada la naturaleza del API. La implementación será desde Ruby
Añadidos docs y tests asociados

PR
https://github.com/Departamento-TI/cenabast-tienda/pull/39
