### ISSUE TITLE
Validación de Usuarios

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#28]
Después que el usuario se ha logueado en la plataforma, utilizando el RUT del usuario como valor de entrada, se deberá consultar el siguiente endpoint para obtener los organismos relacionados del usuario:

Sólo se deberán considerar aquellos valores del “nombreCanal” = “INTERMEDIACION” e “ECOMMERCE”. En definitiva, el usuario RUT 16338556, sólo tiene acceso al organismo Solicitante “S.S. Osorno” y a los organismos Destinatarios “CESFAM RAHUE” y “COSAM ORIENTE”. Sólo el canal “Intermediación” está disponible para este usuario en particular.

**Comment by nmella** [comment]
@LeonardoSantis-AcidLabs 

Como teníamos servicios duplicados, prefiero aclararlo. El servicio que debemos utilizar acá es este:

```ruby
GET https://testaplicacionesweb.cenabast.cl:7001/interoperabilidad/servicios/v1/tienda/destinatarios/88888888
```

```json
[
	{
		"rut_usuario": 88888888,
		"idRelacion": 27930,
		"rutSolicitante": 61608406,
		"solicitante": "HOSPITAL SALVADOR",
		"rutDestinatario": 201892,
		"destinatario": "HOSPITAL SALVADOR GENERAL",
		"canal": 67,
		"nombreCanal": "ECOMMERCE",
		"direccionDespacho": "AV SALVADOR 364"
	},
	{
		"rut_usuario": 88888888,
		"idRelacion": 27931,
		"rutSolicitante": 61608407,
		"solicitante": "INST.DE NEUROCIRUGIA",
		"rutDestinatario": 201892,
		"destinatario": "HOSPITAL SALVADOR GENERAL",
		"canal": 67,
		"nombreCanal": "ECOMMERCE",
		"direccionDespacho": "AV SALVADOR 364"
	}
]
```

**Comment by LeonardoSantis-AcidLabs** [comment]
Gracias por la aclaración, lo tendré presente al tomar esta tarea 👍

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/20)

Trabajo en servicios de API usuarios compradores, proveedores, organismos relacionados (receptor, solicitante, compañias)
Trabajo en capa de actualización/creación de modelos (pendiente)

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/21)

Añadidas validaciones de rut
Trabajo en capa de actualización de datos
Tests de modelo, servicios (api, actualización) escritos
Cambio para permitir que API de receptor/destinatario y la de compañia (datos del proveedor) puedan procesar 1 o N objetos (array).

Pendiente:
Eliminar asociación con receptores/compañias que no vengan en respuesta
Integrar servicio con proceso login post clave unica
Reglas de validación de usuario en base a la información, redireccionamientos

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/22)

Añadidas fabricas, tests para procesamiento de destinatarios
Debugging y Refactorización de API para seguir nuevo formato (cambio de paths, cambio de ruta de autorización, cambio en formato de payloads)

Bloqueante: Problemas en endpoints de Compañias (error 500) y Proveedores. No es posible avanzar con desarrollo de tarea

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/26)

Trabajo en test de servicios, validador de datos de usuarios, seleccion de solicitante/destinatario/tienda
Corrección de modelos en base a resultados de tests

Pendiente:
Documentación de cambios

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/27)

Documentación, añadido i18n, correcciones menores en tests

https://github.com/Departamento-TI/cenabast-tienda/pull/41
