### ISSUE TITLE
Asociación de Solicitantes/Destinatarios

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#29]
Se requiere:
Extraer la data de solicitante y destinatario 

sincronizar la data que viene de la respuesta del API

Guardar la información en el sitio 

Implementar la lógica de cambio de destinatario / solicitante en el front 

Se debe sobre-escribir la data existente con la información que nos da la API de dicho servicio 

Crear los modelos necesario para esta funcionalidad

**Comment by LeonardoSantis-AcidLabs** [comment]
Historia relacionada con PE188-10

PR Relacionado:
https://github.com/Departamento-TI/cenabast-tienda/pull/41
