### ISSUE TITLE
Sincronización de productos

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#45]
Se requiere:  Crear la funcionalidad de importacion de productos para la tienda. la misma debe contemplar algunos aspecto específicos como 

Debe validar con el endpoint de contrato si esta activo un producto 

Deberá poder ser parametrizable la cantidad de productos a importar (Puede ser por categorias o por cantidad o por sku)

Deberá poder ser parametrizable la Frecuencia de importación de productos 

Debera importar y crear el producto en spree respetando el tipo de dato y valor 

Crear la logica en spree que controle el estado activo de un producto basado en la fecha de vigencia del contrato 

Criterio de aceptación 

Siempre se sobreescribirá los atributos desde el origen de los datos (API) a la Tienda. Sin embargo, aquellos atributos que no estén presentes en la API, podrán ser modificados directamente en el backoffice de administración de la Tienda.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/28)
Cambio de opensearch por elasticsearch-oss (7.10.2). como el motor de busqueda en proyecto Cenabast
Probado en ambiente de desarrollo, Corrección de pipeline para usar elasticsearch-oss.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/28)

Cambio de Opensearch a Elastic search ya mergeado a main

Trabajo en pipeline de MageAI, importación de datos desde API de productos, contratos con filtros (semi)hardcodeados funcional.

Pendiente: Envio de datos a Spree mediante API, construcción de API, flexibilización de parametrización en llamado a pipeline, etc.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/28)

Trabajo en pipeline de MageAI, importación de datos desde API de productos, contratos con filtros (semi)hardcodeados funcional.

Pendiente: Envio de datos a Spree mediante API, construcción de API, flexibilización de parametrización en llamado a pipeline, etc.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/02/29)

Trabajo en modelado de datos y estrategía para cargar información relevante de producto con datos provenientes de API
Cenabast::Spree::GenericProduct
Cenabast::Spree::Contract
Cenabast::Spree::Provider

Agregadas relaciones a modelo Spree::Product
Agregados specs y factories relacionadas

Pendiente: Exposición de lectura/modificación de datos mediante Spree V2 Platform API. Envio de datos desde MageAI a Spree mediante API, flexibilización de parametrización en llamado a pipeline, etc.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/01)
Definición de endpoints Spree v2 platform para
GenericProduct, Contract, Provider

Progreso en pipeline de MageAI
Trabajo en colección de postman documentando endpoints de Spree API a utilizar en pipeline

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/04)
Trabajo en actualización de endpoints de Cenabast consumidos por aplicación. Parametrización del path base del API mediante variable de entorno.

Eliminación de Cenabast::Spree::Provider para prefererir modelo de Spree::Vendor (proveniente de gema multivendor)
Trabajo en API de contratos y de vendors
Trabajo en colección de postman documentando endpoints.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/06)

Trabajo en revision endpoints de variantes, contractos, vendors desde Postman. Documentacion de endpoints en progreso mediante colección de Postman

Pendiente: Integrar endpoints con flujo en mage-ai

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/07)

Trabajo en exponer, configurar y probar Spree APIs de productos, clasificaciones, propedades de productos, propiedades, y tiendas
Documentación de endpoints en colección Postman (en progreso)
Añadir traducciones de Spree backoffice en locale ES
Progreso en cliente python de Spree APIs (Mage AI)

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/08)

Añadir traducciones de Spree en devise, doorkeeper en locale ES
Trabajo en API Clients de Clasificaciones, Contratos, Generic Products (ZGEN), Products, Taxons, Variants (Mage AI)

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/11)

Trabajo en import de productos genericos (ZGEN) desde Mage AI a Spree
Creación y actualización de datos

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/12)

PR Parcial mergeado a main

https://github.com/Departamento-TI/cenabast-tienda/pull/57
[[PE188-12] Product Sync (Part 1) by LeonardoSantis-AcidLabs · Pull Request #57 · Departamento-TI/cenabast-tienda](https://github.com/Departamento-TI/cenabast-tienda/pull/57) 


> Eagerly merged due to allow us to work on PLP/PDP with the real data schema
> 
> Added models for handling Cenabast product information. added relationships to Spree::Product
> 
> Cenabast::Spree::GenericProduct, Cenabast::Spree::Contract
> 
> Decorated Spree API methods to facilitate data ingestion
> 
> Progress in Mage AI product sync pipeline
> 
> Changed locale from application from en to es
> 
> Added some translations for certain gems (devise, doorkeeper, spree backend)
> 
> Added related factories

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/13)
Trabajo en insercion de Variantes, Contratos, Stock Items, Stock locations

Pendiente:

Definición de taxonomias y hacer cambios respectivos (A espera de cliente)

Validar info
Parametrización de entrada, 
Permitir flujos individuales o masivos
Testing/Docs
Evaluar atributos que no existan en el api deberian ser administrables desde el BO

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/14)

Parametrización de Pipeline para correr flujos individuales o masivos.
Prueba de ejecución de pipeline desde trigger exitosa
Añadiendo specs de solicitud (request) para endpoints de Spree API.

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/15)
Specs de request terminados

Pendiente:
Documentación 
Evaluar atributos que no existan en el api deberian ser administrables desde el BO
