### ISSUE TITLE
Revisión de la Configuración Inicial 

### ISSUE THREAD

**Issue by nmella** [Departamento-TI/cenabast-tienda#47]
Hola @Saulaccid 

Hoy revisamos los aspectos funcionales de la configuración inicial. Nos quedaron las siguientes dudas:

- [x] La versión de elasticsearch es antigua (7.10 es del 2021). ¿Será posible instalar la última versión? (8.12). Por ahora sólo es relevante el motor de ES, y no es necesario instalar Kibana. 
- [x] No funciona la sección por de defecto de "My Account" para los usuarios compradores. Idealmente debería quedar tal como funciona por defecto para que los usuarios puedan revisar su historial de pedidos. ([2024-03-04_16-10](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/67ac4633-98e4-47e6-8116-b25c33492270))
- [x] El "**logout**" no está funcionando correctamente. Si bien al hacer click vuelve a la pagina de login con el mensaje "*Signed out successfully.*", al recargar la página o intentar logear nuevamente me redirige al sitio con el usuario previamente autentificado. Luego no se puede cambiar de usuario ([logout-test](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/03b704dc-f521-4d24-b7d8-dedffee2fa71)). Entiendo que para desloggear en Keycloak, habría que hacer un llamado a [este endpoint](https://login-dev.cenabast.gob.cl/realms/cenabast/protocol/openid-connect/logout).
- [x] No se puede cambiar el organismo "**Solicitante**". El ingresar con el usuario "88.888.888-8", por defecto carga el organismo solicitante "HOSPITAL SALVADOR". Se intenta cambiar por el organimos "INST.DE NEUROCIRUGIA" pero no es posible. Se espera que al selecionar una nuevo organismo "Solitante", este quede visible. ([2024-03-04_16-06](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/ac8cc293-666f-4a4c-901c-99a723be4576))
- [x] No se puede logear con el *usuario proveedor* "55.555.555-5". Posiblemente porque el RUT del usuario también es un usuario comprador ya que arroja error "*Validation failed: Email has already been taken*". ([log-del-error](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/d8c2f630-0f6c-47e1-b32d-fe20b90eb280)). Queda pendiente validar si existe este escenario o no con el equipo de negocio. Lo que sí creo relevante considerar, es que el *email* podría repetirse en distintos RUTs (Distintos RUTs de personas utilizan el mismo correo institucional => contacto@hospitaldetalca.cl), luego idealmente el "email" no debería ser único, sólo el RUT.
- [x] No pude probar el envio de los emails. Configuré el email "hola@patagon.dev" en la seccion de la tienda ([email-config](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/93b27cd2-127d-4770-8e03-a1c2b32b84ce)) y luego reenvié un [pedido](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/12acc322-a4aa-4e04-8316-a4e2094fc818). Revise en los logs, y no encontré nada raro. También en sidekiq aparece que el job fue procesado [correctamente](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/0d6b09bf-dc51-4388-ab64-0e2024404031). ¿Que puede estar pasando? [Estos](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/df6d3d4a-9165-407f-aa42-1a42a3e56c14) son los valores del archivo ENV.
- [x] Tampoco pude probar el almacenamiento de las imagenes en S3. [Subí una imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/4f60ef9a-8ea1-4556-bb55-8e9a6a43a15d) de un producto, pero me trata de cargar desde "localhost:4000" a pesar que en la configuración está como "[tienda-dev.cenabast.gob.cl](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/9ea9874e-ba65-41ce-981b-351034d3e3da)". [Estos](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/0ee54d5f-5e57-4356-b616-5acfc8161f71) son los valores del archivo ENV. ¿Que podrá estar faltando en la configuracíón ?

Eso por ahora, gracias !

Queda pendiente probar el comportamiento cambiando las asociaciones de los organismos a los usuarios en las respuestas de la API.

cc: @LeonardoSantis-AcidLabs, @GloriaVenegas2024, @Claudioten

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola Nicolas,
Muchas gracias por la revisión.
Voy respondiendo a los comentarios

> La versión de elasticsearch es antigua (7.10 es del 2021). ¿Será posible instalar la última versión? (8.12). Por ahora sólo es relevante el motor de ES, y no es necesario instalar Kibana.

Se trabajó con la ultima versión disponible de elasticsearch-oss, la cual tiene el modelo de licenciamiento libre. Tuve algunos problemas al instalar la 8+. Estaré revisando este cambio posible junto con @Saulaccid.

> No funciona la sección por de defecto de "My Account" para los usuarios compradores. Idealmente debería quedar tal como funciona por defecto para que los usuarios puedan revisar su historial de pedidos. ([2024-03-04_16-10](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/67ac4633-98e4-47e6-8116-b25c33492270))

De momento el botón es un mockup de cuando estuve trabajando en el header. Podemos ligar esto con la pagina de mis ordenes nativa de Spree.

> El "logout" no está funcionando correctamente. Si bien al hacer click vuelve a la pagina de login con el mensaje "Signed out successfully.", al recargar la página o intentar logear nuevamente me redirige al sitio con el usuario previamente autentificado. Luego no se puede cambiar de usuario ([logout-test](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/03b704dc-f521-4d24-b7d8-dedffee2fa71)). Entiendo que para desloggear en Keycloak, habría que hacer un llamado a [este endpoint](https://login-dev.cenabast.gob.cl/realms/cenabast/protocol/openid-connect/logout).

No hemos trabajado en el logout propiamente tal, pero entiendo que tenemos que llamar al endpoint correspondiente. Lo estarémos realizando prontamente.

> No se puede cambiar el organismo "Solicitante". El ingresar con el usuario "88.888.888-8", por defecto carga el organismo solicitante "HOSPITAL SALVADOR". Se intenta cambiar por el organimos "INST.DE NEUROCIRUGIA" pero no es posible. Se espera que al selecionar una nuevo organismo "Solitante", este quede visible. ([2024-03-04_16-06](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/ac8cc293-666f-4a4c-901c-99a723be4576))

No he logrado replicar ese problema, ingreso con el RUN 88.888.888-8 y puedo cambiar el organismo Solicitante de esa forma. Alternando entre los dos disponibles.
El resultado se actualiza en la vista:

https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/5d745527-cff6-43c6-b88e-2032aa99497e
(No se si Github soporta adjuntar videos, estaré enviando esto tambien por Slack)

> No se puede logear con el usuario proveedor "55.555.555-5". Posiblemente porque el RUT del usuario también es un usuario comprador ya que arroja error "Validation failed: Email has already been taken". ([log-del-error](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/d8c2f630-0f6c-47e1-b32d-fe20b90eb280)). Queda pendiente validar si existe este escenario o no con el equipo de negocio. Lo que sí creo relevante considerar, es que el email podría repetirse en distintos RUTs (Distintos RUTs de personas utilizan el mismo correo institucional => [contacto@hospitaldetalca.cl](mailto:contacto@hospitaldetalca.cl)), luego idealmente el "email" no debería ser único, sólo el RUT.

Tiene sentido, por defecto el email tiene validación de tipo unico para Spree. Haremos los cambios para que esto no suceda.

> No pude probar el envio de los emails. Configuré el email "[hola@patagon.dev](mailto:hola@patagon.dev)" en la seccion de la tienda ([email-config](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/93b27cd2-127d-4770-8e03-a1c2b32b84ce)) y luego reenvié un [pedido](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/12acc322-a4aa-4e04-8316-a4e2094fc818). Revise en los logs, y no encontré nada raro. También en sidekiq aparece que el job fue procesado [correctamente](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/0d6b09bf-dc51-4388-ab64-0e2024404031). ¿Que puede estar pasando? [Estos](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/df6d3d4a-9165-407f-aa42-1a42a3e56c14) son los valores del archivo ENV.

Las variables de entorno se ven correctas, y similares a las que utilicé para realizar las pruebas.
A que correo le corresponde esa orden? Por defecto el confirm_email del Spree::OrderMailer enviará los correos al correo asociado a la orden (esto es, @order.email), el cual dependerá del usuario que realizó la orden.

> Tampoco pude probar el almacenamiento de las imagenes en S3. [Subí una imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/4f60ef9a-8ea1-4556-bb55-8e9a6a43a15d) de un producto, pero me trata de cargar desde "localhost:4000" a pesar que en la configuración está como "[tienda-dev.cenabast.gob.cl](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/9ea9874e-ba65-41ce-981b-351034d3e3da)". [Estos](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/0ee54d5f-5e57-4356-b616-5acfc8161f71) son los valores del archivo ENV. ¿Que podrá estar faltando en la configuracíón ?

Las variable de entorno son correctas, lo que sucede es que estamos usando el [modo proxy](https://edgeguides.rubyonrails.org/active_storage_overview.html#proxy-mode) de ActiveStorage. Esto implica que al momento de servir las imagenes en el sitio, el framework crea una URL intermedia, la cual descarga los assets y los sirve desde ahí:

Desde la consola de Rails, puedes hacer la siguiente consulta
`ActiveStorage::Attachment.last.blob.url` para consultar del ultimo adjunto subido, cual es la URL original de la cual se cargan los datos:
"https://patagon-labs.s3.amazonaws.com/v7ev3aykq7u1a06cmly14cioy6io"

Puedes revisar el bucket en S3 y deberías poder ver el archivo adjunto con esa key
Luego utilizando:
```
Rails.application.routes.url_helpers.rails_storage_proxy_url(ActiveStorage::Attachment.last)
```
puedes ver como se transforma el dato a una url proxy, tipo:
"http://localhost:4000/rails/active_storage/blobs/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ac0cc5b14c331b6638d235489b7a6921d4c73b1a/Fondo%20Acid%201.jpg"

Esta configuración la podemos cambiar a modo Redirect, para generar URLs intermedias que redirigen a la URL de servicio final (S3).

https://guides.rubyonrails.org/configuring.html#config-active-storage-resolve-model-to-route

**Comment by nmella** [comment]
Buenísimo, gracias @LeonardoSantis-AcidLabs Se entiende perfecto.

Si sirve, yo probé ES 8 con esto y me funcionó ok agregándolo al docker-compose:

```yaml
elasticsearch:
    image: elasticsearch:8.12.2
    ports:
     - "9200:9200"
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - 'elasticsearch-data:/usr/share/elasticsearch/data'
```

> A que correo le corresponde esa orden? Por defecto el confirm_email del Spree::OrderMailer enviará los correos al correo asociado a la orden (esto es, @order.email), el cual dependerá del usuario que realizó la orden.

[Cambié el email del pedido](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/b59d84a7-8120-44d8-89be-2f9c8c40f65a) que viene por defecto y puse mi email. Y revisando el log, aparece mi email [como destinatario](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/2b102c84-9dc9-4f2c-80fb-3b5785b14a01). Ni idea que puede ser 🤔.

 Ok, probé lo del bucket y sí, me aparece perfecto que [se subió al bucket](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/ecd09b9a-fab8-4eff-98fd-82ffeb68cfed). Aun así [no se ve la imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/cfdf7290-87eb-4b4c-85e5-6f76c0d2e51a) en el panel. ¿Que puede ser?
 
 > No se puede cambiar el organismo "Solicitante". El ingresar con el usuario "88.888.888-8", por defecto carga el organismo solicitante "HOSPITAL SALVADOR". Se intenta cambiar por el organimos "INST.DE NEUROCIRUGIA" pero no es posible. Se espera que al selecionar una nuevo organismo "Solitante", este quede visible. ([2024-03-04_16-06](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/ac8cc293-666f-4a4c-901c-99a723be4576))
 
 Tengo [este error](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/5d5ee7c5-e931-4832-995a-9c2a7aea5cb2) en el navegador...¿Sabes que puede ser? ([2024-03-05_13-02](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/2d1e7b02-aac5-448c-b6ee-9b70ed3de2db))

**Comment by LeonardoSantis-AcidLabs** [comment]
Buenas tardes Nicolas,

Gracias por la ayuda con lo de Elastic, ya con eso que me enviaste lo pude instalar bien y sin problemas.
Estaré subiendo un parche con eso y otras mejoras producto de la revisión.

Voy contestando a las dudas:

> [Cambié el email del pedido](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/b59d84a7-8120-44d8-89be-2f9c8c40f65a) que viene por defecto y puse mi email. Y revisando el log, aparece mi email [como destinatario](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/2b102c84-9dc9-4f2c-80fb-3b5785b14a01). Ni idea que puede ser 🤔.

En mi caso esta es la configuración que utilicé:
- [Orden con mi cuenta](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/3fe10219-1649-45ae-9423-87af68d629ec)
- [Canal de compra asociado a hola@patagon.dev como remitente](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/0594e51d-c8aa-497f-9db7-8a3de9c3f540)
- [Variables de entorno de correo (password redactado)](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/f72b26a0-62f5-46c2-998d-e196d4a392cd)

Al utilizar la opción de reenvio, llega este correo a mi casilla de entrada: [Correo](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/f83835d7-4963-4614-9f29-d0833e21f7f3)
Vale destacar que el correo llegó en mi casilla de "Updates" en Gmail. Quizás en tu caso llegó a una casilla secundaria, o fue marcado como spam por tu casilla de correos. Valdría la pena revisar 🤔

> Ok, probé lo del bucket y sí, me aparece perfecto que [se subió al bucket](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/ecd09b9a-fab8-4eff-98fd-82ffeb68cfed). Aun así [no se ve la imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/cfdf7290-87eb-4b4c-85e5-6f76c0d2e51a) en el panel. ¿Que puede ser?

En mi caso funciona así:
- [Vista imagenes de producto](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/d0ea49e8-ebc5-4677-8b24-2fa38af772d1)
- [Listado de productos](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/71d75539-e97b-456f-a52d-fe2db8f9d097)

Tendrás el log de la aplicación a mano? cuando se le hace la solicitud a la url proxy, se deberían ver entradas de este estilo:
[Logs de aplicación](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/0e193018-c262-4b78-b24d-1c9b2e5a9c04)

> Tengo [este error](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/5d5ee7c5-e931-4832-995a-9c2a7aea5cb2) en el navegador...¿Sabes que puede ser? ([2024-03-05_13-02](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/2d1e7b02-aac5-448c-b6ee-9b70ed3de2db))

Favor adjuntar el output de la llamada al endpoint /api_tokens. Me suena que está retornando una excepción no controlada, cuando debería ser una respuesta JSON.
En mi caso, devuelve esto: [Resuesta JSON /api_tokens](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/fc591e1f-f6d7-46fe-af6a-e1e23b808d64)

**Comment by nmella** [comment]
Gracias. Ya pudimos validar todos los puntos en el ambiente local. 
Todavía tenemos que resolver el problema en nuestro ambiente de desarrollo.

**Comment by nmella** [comment]
Hola @LeonardoSantis-AcidLabs 

Nuestro sysadmin revisó nuestro ambiente de desarrollo y encontró que la aplicación se comporta distinto debido a que el Spree Frontend está utilizando el caché del navegador, y por eso no llega el request al servidor.

Me dice que en el controlador del homepage existe [está](https://github.com/spree/spree_rails_frontend/blob/6f6a77e66d1d51fa568e02cce968fd307ffed21a/app/controllers/spree/home_controller.rb#L17) validación por el valor del `http_cache_enabled` que por defecto estaba como `true`, aunque hace unos días está [este PR](https://github.com/spree/spree_rails_frontend/pull/65/files#diff-59d24954a9c260a3460131e7206e2fa9bc9c450dcf57688b5fe5f557d7f598a2) justamente para dejarlo como `false`. 

Así que por favor podemos dejar el valor por defecto del atributo `http_cache_enabled` en  "**false**" ?

Gracias !

cc: @Claudioten

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola buenos dias, acabo de mergear un pull request que agrega un inicializador, dejando el valor de http_cache_enabled como **false**.
Quedo atento si necesitan mas cambios.

Saludos!

**Comment by nmella** [comment]
Gracias @LeonardoSantis-AcidLabs 

Lo probé y sigue **sin funcionar** en el ambiente de desarrollo. 😭

Le dije a nuestro contacto interno que no funcionaba, y me respondió lo siguiente. ¿Quizás te sirve ?

> Hi Nicolas, 
> I checked this again and find out few things - 
> 1. When we are changing the drodowns, its TURBO STREAM request and we are responding with the redirect, one option to fix this will be to respond with updated turbo frame. 
> 2. Spree cache the entire header with the spree_menu_cache_key(https://github.com/spree/spree_rails_frontend/blob/main/app/helpers/spree/navigation_helper.rb#L34), and our dropdowns are in this header, so its always being served from cache entire expired. 
> 
> So, we either need to update this helper method to implement logic, or move out our header component code from this cache block or implement turbo frame solution. 
> 
> Here is video made explaining the issue - https://www.awesomescreenshot.com/video/25830223?key=6a0fc421d683282d289aa901b586cdc0

Gracias !

**Comment by ncmella** [comment]
@LeonardoSantis-AcidLabs 

A todo esto, creo que no lo mencioné, pero funciona perfecto cuando seleccionó la opción de `disable cache` en el tab de "Network" del navegador. ([imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/3fea1a9f-9250-4b21-b67e-c540eb1800c6))

El problema sigue siendo en el header al cambiar de organismo Solicitante, o haciendo logout/login con distintos usuarios.

Gracias.

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola @nmella muy buenas tardes,

Con ayuda del video de Rahul, logré replicar el problema con mi local al activar el cache y hice un fix en base a las sugerencias.
Así mismo, tambien logré replicar el otro problema que teniamos (visitante se logea, dropdowns aparecen en blanco). Tambien agregué en ese PR un fix para ese defecto:

https://github.com/Departamento-TI/cenabast-tienda/pull/66

Quedo atento 🙌
