### ISSUE TITLE
Correcciones Cenabast Varias [hito 01]

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#51]
Corección de issues encontrados post revisión de Nicolas respecto al hito 1:

- Validación del correo no debe ser unico
- Validación de RUN unico agregada
- Preferencia de “Tienda actual” re-instaurada, para facilitar a usuarios administradores el impersonamiento de todas las Spree::Store
- Actualización a elastic 8.12.2
- Logout ahora termina sesión en Keycloak, utilizando endpoint de /logout
- Modificar comportamiento de botón “Mis ordenes” en header para realmente redirigir a esa vista del sitio
- Tests relacionados

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/05)
Corección de issues encontrados post revisión de Nicolas respecto al hito 1:

Validación del correo no debe ser unico

Validación de RUN unico agregada

Preferencia de “Tienda actual” re-instaurada, para facilitar a usuarios administradores el impersonamiento de todas las Spree::Store

Actualización a elastic 8.12.2

Logout ahora termina sesión en Keycloak, utilizando endpoint de /logout

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/06)

Trabajo en finalizar PR:

Modificar comportamiento de botón “Mis ordenes” en header para realmente redirigir a esa vista del sitio

Tests relacionados

**Comment by LeonardoSantis-AcidLabs** [comment]
PR Mergeado a main
https://github.com/Departamento-TI/cenabast-tienda/pull/49

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/08)

Añadida configuración para acceder a ambientes locales mediante HTTPS.
https://github.com/Departamento-TI/cenabast-tienda/pull/55

Pruebas en ambiente de desarrollo usando HTTPS:
Creación de video de evidencia
(Compartiré el video de evidencia por Slack)

Se realizó navegación relacionados con login/logout, cambio de solicitante/destinatario/tienda, pagina de carro, pagina de mi perfi, y homepage.
Probando RUNs 88.888.888-8, 99.999.999-9, 44.444.444-4
No se encontraron defectos,

**Comment by LeonardoSantis-AcidLabs** [comment]
Por cierto, api_token pareciera cargar correctamente

![Image](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/c439b543-fe97-4c24-afcc-04694966dea7)

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/12)

Se realizaron correcciones asociadas a RUN solicitantes duplicados en header:
[Solicitantes duplicados - Agrupar por RUT · Issue #58 · Departamento-TI/cenabast-tienda](https://github.com/Departamento-TI/cenabast-tienda/issues/58) 

[[PE188-72] Add distinct clause to has_many though relationship of users by LeonardoSantis-AcidLabs · Pull Request #59 · Departamento-TI/cenabast-tienda](https://github.com/Departamento-TI/cenabast-tienda/pull/59)

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/15)
Correcciones asociadas con flag http_cache para ambientes pre-productivos
[Disable Spree::Frontend http_cache_enabled config to always send http request to the server by LeonardoSantis-AcidLabs · Pull Request #62 · Departamento-TI/cenabast-tienda](https://github.com/Departamento-TI/cenabast-tienda/pull/62)

**Comment by LeonardoSantis-AcidLabs** [comment]
(2024/03/18)
Revisión de ambiente desarrollo Cenabast (https://tienda-dev.cenabast.gob.cl/) para identificar problema que evitaba que la vista de homepage se recargara al seleccionar un solicitante/destinatario distinto

![Image](https://github.com/Departamento-TI/cenabast-tienda/assets/156705333/8cbd68cf-a8f2-43b5-a16e-cd6ffe8402e0)


Problema detectado y corregido
