### ISSUE TITLE
Página de lista de productos (PLP, Ecommerce)

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#52]
Se requiere:

La visibilidad del Catálogo de Productos dependerá del Canal seleccionado por el usuario. Las siguientes imágenes ejemplifican los escenarios en que el usuario selecciona el Canal “01 intermediación” y el Canal “67  ecommerce”. Por cada Canal, la visibilidad de los productos será acorde
a los productos habilitados. Para este piloto, sólo se considerará el Canal “67 ecommerce”.

- Listado de productos 
- Card de producto
- Maquetar el filtro
- Vista del buscador sera la misma que la vista de la plp pero poblada con los resultados (Pendiente definición sobre el uso de elasticsearch)
- EL botón de agregar solo te llevara a la vista de la PDP y no tendrá el desplegable para mas opciones

**Comment by FelipeFabio-Acid** [comment]
En relación al levantamiento del ambiente de desarrollo realicé las siguientes modificaciones al código: 

- Actualicé el README indicando la versión mínima del engine de Docker para correr el proyecto
- Corregí el seed de creación de stores porque generaba error por falta de información
- Incorporé la definición de rut para el seed de user/admin
- Actualicé la gema Yard por vulnerabilidad encontrada por Bundle Audit

PR #53

**Comment by FelipeFabio-Acid** [comment]
#54 PR de PLP, falta validación y code review.

Evidencias en PR.
