### ISSUE TITLE
Solicitantes duplicados - Agrupar por RUT

### ISSUE THREAD

**Issue by ncmella** [Departamento-TI/cenabast-tienda#58]
Hola @LeonardoSantis-AcidLabs 

La visibilidad de los organismos solicitantes **debe estar agrupada por RUT.** No sé si esto no estuvo claro en el prototipo o se me fue detallarlo en el documento de requerimientos, pero debemos mostrar sólo 1 vez cada organismo.

Por ejemplo, actualmente el RUT: 88.888.888-8 tiene asociado 2 organismos solicitantes (2 RUT):

- RUT: 70856400 (MUNIC SAN CARLOS) 
- RUT: 61606918 (CORP.MUNIC.PUENTE ALTO)

Y la vista actual es [así](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/513fa289-5b20-4819-92cf-d7a5a3b02e2e), pero debería ser [así](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/1c8bbd8d-eb23-4abd-9412-8a8bf42384f6).

Lo otro es que después de cambiar los organimos del endpoint al RUT 55.555.555-5, ahora no queda por defecto ningún organismo "preseleccionado". ([imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/40626ec2-1248-48bd-948f-9dd75fe685ea)) ¿Puedes revisar si te pasa lo mismo?

Gracias.

cc: @Claudioten, @GloriaVenegas2024, @Saulaccid

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola Nicolas buenas tardes por acá 😀

Mergeé un PR con la corrección para evitar registros duplicados, en efecto cuando un usuario tenia muchos organismos receptores asociados al mismo solicitante, se mostraba ese solicitante repetido por la cantidad de receptores asociados. Se agrego una clausula para eliminar los duplicados.
https://github.com/Departamento-TI/cenabast-tienda/pull/59

> Lo otro es que después de cambiar los organimos del endpoint al RUT 55.555.555-5, ahora no queda por defecto ningún organismo "preseleccionado". ([imagen](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/40626ec2-1248-48bd-948f-9dd75fe685ea)) ¿Puedes revisar si te pasa lo mismo?

No he logrado replicar este comportamiento exactamente. Me logeo con el usuario 55.555.555-5 varias veces pero no observo anomalias

Lo mas parecido que he visto es cuando estoy logeado con un usuario administrador, y le quito los permisos de administrador cuando tiene la sesión abierta.
En ese caso, el selector de solicitante/destinatario se puede ir a blanco, en el caso que la selección ya no se encuentre dentro de los posibles valores (eso dado que el admin puede elegir todo, pero los usuarios compradores normales solo pueden elegir lo que tienen explicitamente designado).

**Comment by nmella** [comment]
OK, gracias Leo !

> No he logrado replicar este comportamiento exactamente. Me logeo con el usuario 55.555.555-5 varias veces pero no observo anomalias.

Si logro replicarlo te aviso.
