### ISSUE TITLE
Instalación base de la tienda

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#6]
Tras un análisis técnico de la organización, se ha decidido implementar el proyecto piloto de Tienda utilizando como base la plataforma de ecommerce Spree Commerce, plataforma basada en el framework Ruby on Rails. Los siguientes componentes han sido validados y deberán ser utilizados en
el proyecto:

Última versión Spree Commerce version (4.7.x).

Gema Spree Starter Dockerize para llevar la aplicación en contenedor.

Se requiere validar el contenido del repositorio actual y ajustar de ser necesario

**Comment by Saulaccid** [comment]
Crear un readme de instalación.

**Comment by LeonardoSantis-AcidLabs** [comment]
Instalación en ambiente local completada con exito, se creo una rama con algunas mejoras relacionadas con la instalación en ambientes locales.

README editado con detalles de como realizar instalación.
#13 PE188-4-5-6-add-base-instalation-configuration

Esta rama tambien abordará la tareas
`PE188-5: Configuración base de tienda Spree`
e `PE188-6: Instalación de Gemas base`
