### ISSUE TITLE
Checkout y sus reglas

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#63]
Para el Canal “67 ecommerce”, el carro de compras se comportará como típicamente lo hace un carro en un ecommerce tradicional. Este canal no está contemplado en el piloto.

➔ Agrupar productos por Proveedor.
➔ La compra mínima debe ser mayor a 4 UTM por Proveedor, de lo contrario, no podrá iniciar el Checkout.
➔ El Carro deberá estar relacionado al organismo “Destinatario” y al
“Canal” seleccionado. Luego, distintos usuarios que tengan acceso al mismo “Destinatario” y “Canal” verán el mismo Carro de Compra.

**Comment by nmella** [comment]
> Este canal no está contemplado en el piloto.

Sólo aclarar que el canal "ecommerce" **sí debemos incluirlo en el piloto**. Por un cambio en el requerimiento, y por un tema de "forma" quedó como que no debemos contemplarlo.

**Comment by FelipeFabio-Acid** [comment]
Comparto PR de la tarea con:
- asociación de las ordenes de compra con el destinatario
- creación de 2 campos para el manejo del valor mínimo de compra por proveedor
#69 

Una vez aprobado este PR pasaré a integrarlo con la maquetación del carro de compra

**Comment by FelipeFabio-Acid** [comment]
Se cerró con merge el PR #69 las funcionalidades ya se encuentran en main.


![Image](https://github.com/Departamento-TI/cenabast-tienda/assets/156840296/115d65b2-b685-4914-8d9d-77ba6df8a374)
![Image](https://github.com/Departamento-TI/cenabast-tienda/assets/156840296/0c4b5c4c-602e-4aa0-bb3d-6a3f62a16858)
