### ISSUE TITLE
Instalación de Gemas base

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#7]
Instalar gemas base indispensables para la realización del proyecto:

Gema Spree Starter Dockerize para llevar la aplicación en contenedor.

Gema Spree Legacy frontend como plataforma de frontend.

Gema Spree Multi-Vendor para habilitar la funcionalidad de Marketplace multiproveedor.

pg para manejo de base de datos relacional

Sidekiq para tareas en segundo plano

Rubocop para analisis estatico de codigo

**Comment by LeonardoSantis-AcidLabs** [comment]
Se instalaron las gemas indicadas en el proyecto:
* Spree Starter Dockerize
* Spree Legacy frontend
* Spree Multi-Vendor
* pg
* Sidekiq
* Rubocop

Los cambios están en la rama
https://github.com/Departamento-TI/cenabast-tienda/pull/13 PE188-4-5-6-add-base-instalation-configuration

Esta rama tambien abordará las tareas
`PE188-4: Instalación base de la tienda ` y `PE188-6: Instalación de Gemas base`

 .
