### ISSUE TITLE
Error en el carro cuando el producto tiene una imagen

### ISSUE THREAD

**Issue by nmella** [Departamento-TI/cenabast-tienda#71]
Hola,

Se produce este error en el carro cuando el producto tiene una imagen:

![2024-03-26_15-21](https://github.com/Departamento-TI/cenabast-tienda/assets/5648244/7654017d-06fb-484f-a50a-022769aeee42)

Para replicar el error, basta agregar una imagen al producto, y luego agregarlo al carro.

cc: @LeonardoSantis-AcidLabs, @Saulaccid

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola Nicolas buenos dias, gracias por el reporte
Etiqueto a @FelipeFabio-Acid que estuvo trabajando en esa vista.

**Comment by FelipeFabio-Acid** [comment]
hola @nmella , en qué rama estás levantando el proyecto, main?

**Comment by nmella** [comment]
> hola @nmella , en qué rama estás levantando el proyecto, main?

Sip.

**Comment by LeonardoSantis-AcidLabs** [comment]
Hola chicos perdón por la demora,
ya revisé el PR, se ve bien.

**Comment by FelipeFabio-Acid** [comment]
Listo @nmella ya mergeado el fix en main.
