### ISSUE TITLE
Últimos pendientes 🚀

### ISSUE THREAD

**Issue by ncmella** [Departamento-TI/cenabast-tienda#76]
Hola equipo 👋! 

Para poder ir avanzando en el cierre del proyecto piloto, dejo aquí estos 2 puntos pendientes que debemos abordar:

- [ ] Del hito 1 dejamos [pendiente](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/38170944-8893-464c-a392-0f342941b076) el "Login de proveedor". Cuando se logea un usuario proveedor, éste debería ser redirigido al panel de administración, y poder visualizar sus productos y pedidos.
- [ ] ¿Al parecer no es posible modificar las categorias principales desde el panel de admin? ([image](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/630ca3d3-5a7f-4021-8169-98590d2370c8)) 

También dejo este otro grupo de "detalles" que tienen baja prioridad. En relidad, antes que resolver estos puntos, sería ideal abordar el "prellenado" del carro con la [demanda programada](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/1018f800-e095-497c-8aa9-750e54fe7bb1) para el canal intermediación (quedó fuera del alcance, pero estaba la idea de abordarlo en caso que "quedase" tiempo) 

- El buscador no funciona. Ideal sería buscar por nombre y SKU. ([image](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/8b04fdd3-0e42-4f19-a2cd-2e2cd4295079)). 
- El contador de unidades del ícono del carro no funciona. ([image](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/c3c5d141-36c6-4967-b16c-04ffc1f794c4))
- El carro de la tienda de intermediación me da [este](https://github.com/Departamento-TI/cenabast-tienda/assets/147117542/4cb2002d-80ae-4530-85fa-ef7673ccebf7) error. 

Queda pendiente revisar los creación de pedidos en SAP.

Gracias !

cc: @Claudioten, @Saulaccid, @LeonardoSantis-AcidLabs, @FelipeFabio-Acid

**Comment by Saulaccid** [comment]
ok recibido

lo vemos en la reunión de hoy
