### ISSUE TITLE
Configuración base de tienda Spree 

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#8]
Luego de realizar la instalación se requiere validar que la configuración de la tienda base este realizada correctamente: 

Se debe garantizar que pueda iniciar el desarrollo en el ambientes locales de la aplicación 

Validar integración con respositorio. Definir estrategía de branching

Estategía de branching deberá ser parte del Readme.

Construir pipeline usando Github Actions

Pipeline debe correr herramientas de monitoreo estatico (Rubocop), entre otros

Rspec

Configuración de Git hooks

**Comment by LeonardoSantis-AcidLabs** [comment]
Ajustes en configuración local (zona horaria, nombres de data stores, suite de test, idioma de localización, etc) para proyecto


Se agregó en README detalles de estrategía de branching a seguir

Añadido Github Action pipeline de Lint y Test
* Pipeline de Lint comprende llamada a Rubocop (estilo de codigo), Bundle-audit (vulnerabilidades de gemas), Brakeman (alertas de seguidad) e Slim-lint (lint de vistas)
* Pipeline de Lint ejecuta Rspec

Añadida configuración de Overcommit que permite correr git hooks previos a commits y pushes. En estos hooks se correrán localmente los linters de estilo.



Los cambios están en la rama
https://github.com/Departamento-TI/cenabast-tienda/pull/13 PE188-4-5-6-add-base-instalation-configuration

Esta rama tambien abordará las tareas
PE188-4: Instalación base de la tienda  y PE188-6: Instalación de Gemas base
