### ISSUE TITLE
Analisis y propuesta de Gemas adicionales

### ISSUE THREAD

**Issue by Saulaccid** [Departamento-TI/cenabast-tienda#9]
Se requiere:
Generar un documento respaldando y listando el uso de las gemas adicionales no contempladas en el documento de requerimiento

**Comment by LeonardoSantis-AcidLabs** [comment]
Se agregó información sobre las Gemas utilizadas (actualmente) y gemas propuestas.
Se describe cuales serían las potenciales ventajas de utilizar las gemas propuestas.
Se actualizaron las pautas para desarrolladores con información sobre trunk based development, linters, tests y otros temas.

https://github.com/Departamento-TI/cenabast-tienda/pull/18

Esta información quedó en la documentación del proyecto (carpeta `docs`). Accesible desde https://departamento-ti.github.io/cenabast-tienda .
